# Generated by Django 4.2.2 on 2023-06-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, upload_to='project_images')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
